export const datas = [
  {
    author: {
      username: "ajibola",
      profilePics: "profile.png",
    },
    likes: [],
    shares: [],
    _id: "67f252e0cbc885044d11b7e6",
    title: "What can i build with ruby?",
    body: "<p>Ruby is a super flexible language, best known for its simplicity and clean syntax. While it's not as trendy as it once was, especially in startups, it’s still a great language to build with — especially when paired with <strong>Ruby on Rails</strong>, its most famous web framework.</p><p>Here’s what you can build with Ruby:</p><h3>🧱 Web Applications</h3><p><strong>Ruby on Rails</strong> makes it crazy fast to build full-stack web apps.</p><ul><li>Blogs, forums, marketplaces (like Etsy clones)</li><li>SaaS platforms (like project management tools)</li><li>Social networks (like early Twitter — which was originally built with Rails)</li><li>Booking systems or CRMs</li></ul><h3>🔧 APIs / Backends</h3><p>Rails or <strong>Sinatra</strong> (a minimal framework) can power REST or GraphQL APIs.</p><ul><li>Mobile app backends</li><li>Headless CMS</li><li>Microservices</li></ul><h3>💻 Command-Line Tools / Scripts</h3><p>Ruby is awesome for scripting, especially for DevOps or automation.</p><ul><li>File renamers, backup scripts, report generators</li><li>Deployment tools</li><li>Cronjob scripts</li></ul><h3>🎮 Games (though not the go-to)</h3><p>You can build simple 2D games using gems like:</p><ul><li><strong>Gosu</strong> – for game development (good for small 2D games)</li><li><strong>Ruby2D</strong> – beginner-friendly 2D game library</li></ul><p>But for serious games, C++/C#/JS is more common.</p><h3>🤖 Bots and Automation</h3><p>You can build:</p><ul><li>Discord or Slack bots</li><li>Web scraping bots (e.g., with <strong>Nokogiri</strong>)</li><li>Twitter/X automation bots (using APIs)</li></ul><h3>📊 Data Processing / ETL</h3><p>Ruby can do data processing, though Python is more popular now.</p><ul><li>CSV, JSON, XML processors</li><li>Small ETL pipelines</li><li>Custom report generators</li></ul><h3>🧪 Testing / QA Tools</h3><p>Ruby is used in automation testing — many QA teams love:</p><ul><li><strong>RSpec</strong> – for testing Ruby code</li><li><strong>Capybara</strong> – for simulating user actions in browsers</li><li><strong>Cucumber</strong> – for behavior-driven development</li></ul><h3>💡 Some Fun Ideas to Try</h3><ul><li>A personal budget tracker (Rails + SQLite/Postgres)</li><li>A simple blog engine (Rails or Sinatra)</li><li>A meme generator CLI</li><li>A URL shortener</li><li>A job board</li><li>A Ruby game with Gosu</li><li>A daily quote Slack bot</li></ul><p><br></p>",
    imageUrl: "ruby.webp",
    category: "first",
    createdAt: "2025-04-06T10:09:36.378Z",
    updatedAt: "2025-04-07T16:26:58.314Z",
    __v: 0,
    comments: [
      {
        id: "67f14c0d9c858abf09ce2837",
        username: "neverthelesse",
        profilePics: "profile.png",
        comment: "what a nice post",
      },
      {
        id: "67f14c389c858abf09ce2839",
        username: "micheal",
        profilePics: "profile.png",
        comment: "i really like this post",
      },
      {
        id: "67f242e17b82f7232e77d057",
        username: "ajibola",
        profilePics: "profile.png",
        comment: "what a cool post",
      },
      {
        id: "67f242e17b82f7232e77d057",
        username: "ajibola",
        profilePics: "profile.png",
        comment: "i really like the post",
      },
      {
        id: "67f242e17b82f7232e77d057",
        username: "ajibola",
        profilePics: "profile.png",
        comment: "that's my comment",
      },
      {
        id: "67f242e17b82f7232e77d057",
        username: "ajibola",
        profilePics: "profile.png",
        comment: "what a nice post",
      },
    ],
  },
  {
    author: {
      username: "neverthelesse",
      profilePics: "profile.png",
    },
    likes: [],
    shares: [],
    _id: "67f3feabe77ef2b359a9b19f",
    title: "how to use findByIdandupdate mongosh, by pushing into an array",
    body: "hello world",
    imageUrl: "mongo.webp",
    category: "first",
    createdAt: "2025-04-07T16:34:51.229Z",
    updatedAt: "2025-04-10T15:48:45.622Z",
    __v: 0,
    comments: [
      {
        id: "67f14c0d9c858abf09ce2837",
        username: "neverthelesse",
        profilePics: "profile.png",
        comment: "mongodb or mysql",
      },
      {
        id: "67f14c0d9c858abf09ce2837",
        username: "neverthelesse",
        profilePics: "profile.png",
        comment: "wow",
      },
    ],
  },
  {
    author: {
      username: "neverthelesse",
      profilePics: "profile.png",
    },
    _id: "67f5368ca56ded8a46247619",
    title: "Why everybody is running into machine learning",
    body: "<h2>Why Everybody Is Running into Machine Learning</h2><p>Over the past decade, machine learning (ML) has transformed from a niche academic field into a global phenomenon influencing nearly every industry. Whether it's your social media feed, your music recommendations, or the fraud detection system used by your bank, chances are machine learning is working behind the scenes. So, why is everyone—from startups to tech giants to everyday developers—rushing into machine learning? Let's dive deep into the reasons behind this massive shift.</p><h3>1. <strong>The Data Explosion</strong></h3><p>We are creating data at an unprecedented rate. Every swipe, click, search, and sensor generates a small piece of data. With the rise of IoT, smartphones, cloud computing, and digital services, the world now produces <strong>trillions of gigabytes of data each day</strong>.</p><p>But data on its own isn’t valuable—<strong>it's how you make sense of it that counts</strong>. Enter machine learning. ML algorithms thrive on large datasets, using them to uncover patterns, make predictions, and even generate new content. As data becomes more abundant, the hunger for machine learning grows.</p><h3>2. <strong>Accessibility and Open-Source Culture</strong></h3><p>A decade ago, ML was largely confined to research labs with limited access to tools and infrastructure. Today, it's more accessible than ever:</p><ul><li><strong>Frameworks like TensorFlow, PyTorch, and scikit-learn</strong> have made ML easier to learn and implement.</li><li><strong>Pretrained models</strong> for vision, language, and audio are available freely.</li><li><strong>Cloud providers</strong> like AWS, Google Cloud, and Azure offer ML as a service, removing the need for expensive infrastructure.</li><li><strong>Online courses</strong> from platforms like Coursera, edX, and Udacity have democratized ML education.</li></ul><p>This open-source and educational boom has allowed millions of developers, researchers, and even hobbyists to experiment with machine learning.</p><h3>3. <strong>Business Value and Competitive Advantage</strong></h3><p>Machine learning provides <strong>real business value</strong> in the form of:</p><ul><li><strong>Increased automation</strong></li><li><strong>Enhanced customer experience</strong></li><li><strong>Operational efficiency</strong></li><li><strong>Predictive analytics</strong></li></ul><p>Companies that adopt ML can often <strong>make better decisions faster</strong>, optimize operations, and understand customers more deeply. In competitive markets, ML has become a key differentiator. Businesses are no longer asking <em>if</em> they should use ML, but <em>how fast</em> they can implement it.</p><p>From recommendation engines on Netflix to fraud detection in fintech to supply chain forecasting in retail, ML is being used to cut costs and unlock new revenue streams.</p><h3>4. <strong>The Rise of Generative AI</strong></h3><p>The explosion of <strong>generative AI</strong>—systems like GPT (language), DALL·E (images), and Sora (video)—has captured global attention. These tools are not only powerful but creative, capable of producing human-like text, music, images, and even code.</p><p>This wave has lowered the barrier even further. You don’t need a PhD to start using AI creatively. With APIs and user-friendly tools, <strong>anyone can integrate generative AI into their product or workflow</strong>, driving a new wave of ML adoption across industries, from marketing to entertainment to software development.</p><h3>5. <strong>The FOMO Factor</strong></h3><p>Let’s be honest—<strong>fear of missing out (FOMO)</strong> is real. As more companies embrace ML, the pressure mounts on others to follow suit or risk falling behind. Investors now expect ML-driven roadmaps. Job seekers want to work with AI. Customers expect smarter services.</p><p>This bandwagon effect creates a self-reinforcing cycle: the more people jump into ML, the more momentum it gains, pushing others to get involved just to stay relevant.</p><h3>6. <strong>Advancements in Hardware</strong></h3><p>Machine learning requires intense computational power, especially for training deep learning models. Thankfully, <strong>hardware has kept up</strong>:</p><ul><li><strong>GPUs and TPUs</strong> have drastically sped up model training.</li><li><strong>Edge computing</strong> allows ML to run on devices like phones and cameras.</li><li><strong>Energy-efficient chips</strong> make deploying ML models in real-time environments possible.</li></ul><p>This hardware progress makes ML not just feasible but performant at scale, enabling applications in self-driving cars, drones, robotics, and AR/VR.</p><h3>7. <strong>The Job Market is Booming</strong></h3><p>Careers in machine learning and AI are among the most lucrative and in-demand:</p><ul><li>Data scientists</li><li>ML engineers</li><li>AI product managers</li><li>Research scientists</li></ul><p>Companies are hiring aggressively, and universities are creating entire departments for AI. Even non-tech professionals—marketers, designers, managers—are learning ML basics to stay competitive.</p><h3>8. <strong>Solving Real-World Problems</strong></h3><p>Machine learning isn't just about profit—it's solving some of humanity's most complex challenges:</p><ul><li><strong>Healthcare:</strong> ML is helping detect diseases, personalize treatments, and manage patient data.</li><li><strong>Climate:</strong> ML models are improving weather forecasting and optimizing energy use.</li><li><strong>Agriculture:</strong> AI is helping farmers monitor crop health, predict yields, and reduce waste.</li><li><strong>Education:</strong> Adaptive learning platforms tailor instruction to each student's needs.</li></ul><p>These meaningful applications attract not just businesses but researchers, nonprofits, and governments.</p><h3>9. <strong>ML is Becoming the New Literacy</strong></h3><p>Much like computers and the internet redefined literacy in the 20th century, <strong>ML is shaping what it means to be “digitally literate” today</strong>. Understanding how machine learning works—even at a conceptual level—is increasingly necessary in modern workplaces.</p><p>As it integrates deeper into our tools and decision-making systems, understanding ML will become as fundamental as knowing how to use spreadsheets or email.</p><h2>Final Thoughts</h2><p>Machine learning is not just a trend—it's a paradigm shift. Like electricity or the internet, it's becoming <strong>a foundational layer</strong> of technology. Whether you're a developer, a business leader, a student, or a curious thinker, now is the time to understand how machine learning works and how it’s changing the world.</p><p>So yes—everybody is running into machine learning. But maybe it’s not a sprint or a race—it’s a transformation. And like all transformations, those who adapt, learn, and build will shape the future.</p>",
    imageUrl: "ai.webp",
    likes: [],
    comments: [
      {
        id: "67f14c0d9c858abf09ce2837",
        username: "neverthelesse",
        profilePics: "profile.png",
        comment: "Is machine learning also an AI?",
      },
    ],
    shares: [],
    category: "first",
    createdAt: "2025-04-08T14:45:32.862Z",
    updatedAt: "2025-04-08T14:46:27.174Z",
    __v: 0,
  },
  {
    author: {
      username: "neverthelesse",
      profilePics: "profile.png",
    },
    _id: "67f7d7fea5e51759a46b3957",
    title: "how to be a good photograher",
    body: "<p>being a good photographer</p><h2>being a good photographer</h2><h3>being a good photographer</h3>",
    imageUrl: "photo.webp",
    likes: [],
    comments: [],
    shares: [],
    category: "first",
    createdAt: "2025-04-10T14:38:54.772Z",
    updatedAt: "2025-04-10T14:38:54.772Z",
    __v: 0,
  },
  {
    author: {
      username: "neverthelesse",
      profilePics: "profile.png",
    },
    _id: "1",
    title: "how to drive a car like a pro",
    body: "<h1>Why react is the best library</h1><h2>make sure you close your eye before driving</h2><p>drink<strong> atlease 20bottles of henessy</strong></p>",
    imageUrl: "react.jpg",
    likes: [],
    comments: [],
    shares: [],
    category: "first",
    createdAt: "2025-04-10T15:52:42.098Z",
    updatedAt: "2025-04-10T15:52:42.098Z",
    __v: 0,
  },
  {
    author: {
      username: "neverthelesse",
      profilePics: "profile.png",
    },
    _id: "2",
    title: "Top 10 Programming lanugage",
    body: "<h1>how to drive a car like a pro</h1><h2>make sure you close your eye before driving</h2><p>drink<strong> atlease 20bottles of henessy</strong></p>",
    imageUrl: "programming.webp",
    likes: [],
    comments: [],
    shares: [],
    category: "first",
    createdAt: "2025-04-10T15:52:42.098Z",
    updatedAt: "2025-04-10T15:52:42.098Z",
    __v: 0,
  },
  {
    author: {
      username: "neverthelesse",
      profilePics: "profile.png",
    },
    _id: "3",
    title: "Vue or Angular",
    body: "<h1>how to drive a car like a pro</h1><h2>make sure you close your eye before driving</h2><p>drink<strong> atlease 20bottles of henessy</strong></p>",
    imageUrl: "vue.webp",
    likes: [],
    comments: [],
    shares: [],
    category: "first",
    createdAt: "2025-04-10T15:52:42.098Z",
    updatedAt: "2025-04-10T15:52:42.098Z",
    __v: 0,
  },
  {
    author: {
      username: "neverthelesse",
      profilePics: "profile.png",
    },
    _id: "4",
    title: "All about software Developer",
    body: "<h1>how to drive a car like a pro</h1><h2>make sure you close your eye before driving</h2><p>drink<strong> atlease 20bottles of henessy</strong></p>",
    imageUrl: "software.webp",
    likes: [],
    comments: [],
    shares: [],
    category: "first",
    createdAt: "2025-04-10T15:52:42.098Z",
    updatedAt: "2025-04-10T15:52:42.098Z",
    __v: 0,
  },
];
